policy:
  approval: []
approval_rules:
  - name: growthbook-required
    requires:
      count: 0
      conditions:
        has_status:
          conclusions: [success]
          statuses:
            - Validate GrowthBook Link
